# Generated by Django 5.2.1 on 2025-06-07 08:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='Student ID')),
                ('program', models.CharField(choices=[('Human Resource Management', 'Human Resource Management'), ('Business Administration', 'Business Administration'), ('Accountancy', 'Accountancy'), ('Nursing and Midwifery', 'Nursing and Midwifery'), ('Information and Communication Technology', 'Information and Communication Technology')], max_length=45, verbose_name='Program')),
                ('year', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='Year of Study')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valid_student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='Position')),
                ('manifesto', models.TextField(verbose_name='Manifesto')),
                ('photo', models.ImageField(upload_to='candidate_photos/%Y/%m/', verbose_name='Candidate Photo')),
                ('approved', models.BooleanField(default=False, verbose_name='Approval Status')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('valid_student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='vote.validstudent')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('voted', models.BooleanField(default=False, verbose_name='Has Voted?')),
                ('valid_student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voter', to='vote.validstudent')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('voter_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('device_info', models.TextField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_votes', to='vote.candidate')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='vote.voter')),
            ],
            options={
                'unique_together': {('voter', 'candidate')},
            },
        ),
    ]
