# Generated by Django 5.2.1 on 2025-06-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_alter_vote_unique_together_vote_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='approved',
            field=models.BooleanField(default=None, null=True, verbose_name='Approval Status'),
        ),
    ]
