# Generated by Django 5.2.1 on 2025-06-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_alter_candidate_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountdownTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timer_type', models.CharField(choices=[('application', 'Candidate Application'), ('voting', 'Voting')], max_length=20, unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
    ]
