# Generated by Django 5.2.1 on 2025-06-28 07:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_countdowntimer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Candidate Photo'),
        ),
    ]
